"""Repository contracts owned by the domain, implemented by infrastructure."""

from typing import Protocol

from app.domain.entities import ChartInterpretationMemo, Client, ClientOverview, NatalChart


class ClientRepository(Protocol):
    def add(self, client: Client) -> Client: ...
    def get(self, client_id: int, *, for_update: bool = False) -> Client | None: ...
    def list_overviews(self, search: str | None = None) -> list[ClientOverview]: ...
    def count(self) -> int: ...
    def count_with_chart(self) -> int: ...
    def get_chart(self, client_id: int) -> NatalChart | None: ...
    def save_chart(self, chart: NatalChart) -> NatalChart: ...
    def list_chart_memos(self, client_id: int) -> list[ChartInterpretationMemo]: ...
    def upsert_chart_memos(
        self, client_id: int, memos: list[ChartInterpretationMemo]
    ) -> list[ChartInterpretationMemo]: ...
    def rollback(self) -> None: ...
